### ISSUE TITLE
my keyboard doesnt have lights

### ISSUE THREAD

**Issue by hexalellogram** [billwi/KeyboardLightDance#1]
actually i dont have a scroll lock light, and my caps lock light is broken, and since im on macos numlock serves no purpose and doesnt work basically

**Comment by cool00geek** [comment]
The required APIs are unavailable in the macOS and *nix versions of Java. In other words - it only works on Windows. So this would not work for you anyway. Sorry!

**Comment by hexalellogram** [comment]
tfw @billwi makes a program that does NOT work on Linux
